#!/bin/bash
source hooks/_env

manifestPush(){
  local version=$1
  local images
  for arch in ${X86} ${ARM} ; do
    images+="${DOCKER_REPO}:${arch}-${version} "
  done
  echo "**** Creating manifest ${DOCKER_REPO}:${version} ****"
  docker manifest create ${DOCKER_REPO}:${version} ${images}
  for arch in ${X86} ${ARM} ; do
    echo "**** Annotating manifest ${DOCKER_REPO}:${arch}-${version} ****"
    docker manifest annotate ${DOCKER_REPO}:${version} ${DOCKER_REPO}:${arch}-${version} --os linux --arch $(manifestArch ${arch})
  done
  echo "**** Pushing manifest ${DOCKER_REPO}:${version} ****"
  docker manifest push --purge ${DOCKER_REPO}:${version}
}


for arch in ${X86} ${ARM} ; do
  echo "**** Pushing ${arch}-${GIT_BRANCH} ****"
  docker push "${DOCKER_REPO}:${arch}-${GIT_BRANCH}"
done
manifestPush ${GIT_BRANCH}
