#!/usr/bin/with-contenv bash
set -x

[[ -n ${WHITELIST} && -z ${ALLOW_LIST} ]] && ALLOW_LIST=${WHITELIST}
if [[ -n ${ALLOW_LIST} ]]; then
  for domain in ${ALLOW_LIST//[;,]/ }; do
    domain=$(echo "$domain" | sed 's/^.*:\/\///;s/\/.*$//')
    echo "Enabling connection to host ${domain}"
    iptables  -A OUTPUT -o eth0 -d "${domain}" -j ACCEPT
    ip6tables -A OUTPUT -o eth0 -d "${domain}" -j ACCEPT
  done
fi